services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    restart: always

# В майбутньому сюди можна додати фронтенд, якщо захочете запускати все разом в Docker
